# Generated by Django 4.2.1 on 2023-06-06 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mainTitle', models.CharField(max_length=50, verbose_name='Title')),
                ('mainContent', models.TextField(verbose_name='Opisanie')),
            ],
        ),
    ]
